apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: local-lab
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.40.5
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
        - .metadata.annotations."helm.sh/resource-policy"
        - .metadata.annotations."meta.helm.sh/release-name"
        - .metadata.annotations."meta.helm.sh/release-namespace"
        - .metadata.labels."app.kubernetes.io/managed-by"
        - .spec.versions[].schema.openAPIV3Schema
        - .spec.versions[].subresources
        - .spec.versions[].additionalPrinterColumns
        - .status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  info:
    - name: purpose
      value: Progressive delivery controller for canary analysis and promotion.
