# Default values for helm-guestbook.

replicaCount: 1
revisionHistoryLimit: 3

fullnameOverride: guestbook-ui

image:
  repository: gcr.io/google-samples/gb-frontend
  tag: v5
  pullPolicy: IfNotPresent

containerPort: 80

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  path: /
  pathType: Prefix
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

traefikIngressRoute:
  enabled: true
  entryPoints:
    - web
  match: Host(`guestbook.localhost`)

telemetry:
  enabled: true
  apacheLogDir: /var/log/apache-otel
  otelCollectorEndpoint: otel-collector.observability.svc.cluster.local:4317
  sidecarImage:
    repository: otel/opentelemetry-collector-contrib
    tag: 0.110.0
    pullPolicy: IfNotPresent

probes:
  readiness:
    path: /doesnotexist
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  liveness:
    path: /
    initialDelaySeconds: 15
    periodSeconds: 20
    timeoutSeconds: 2
    failureThreshold: 3

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
