apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: local-lab
  namespace: argocd
spec:
  description: Local reliability lab project for ArgoCD-managed workloads.
  sourceRepos:
    - '*'
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: ai-lab
      server: https://kubernetes.default.svc
    - namespace: observability
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
