apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

configMapGenerator:
  - name: prometheus-config
    files:
      - config/prometheus/prometheus.yml
      - alerts.yml=config/prometheus/alerts.yml
  - name: grafana-datasources
    files:
      - datasources.yaml=config/grafana/datasources.yaml
  - name: grafana-dashboards-provider
    files:
      - dashboards.yaml=config/grafana/dashboards.yaml
  - name: grafana-dashboards
    files:
      - guestbook-overview.json=config/grafana/guestbook-overview.json
      - ai-docqa-overview.json=config/grafana/ai-docqa-overview.json
      - argocd-control-plane.json=config/grafana/argocd-control-plane.json

resources:
  - namespace.yaml
  - blackbox-exporter.yaml
  - prometheus.yaml
  - grafana.yaml
  - otel-collector.yaml
  - ingressroute.yaml
  - load-generator.yaml
