apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - name: argocd-server
          args:
            - /usr/local/bin/argocd-server
            - --insecure
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-reliability-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/edwardmccormick/argocd-example-apps.git
    targetRevision: main
    path: environments/local
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
